import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidePar from "@/components/SidePar";
import Navbar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className=" bg-gray-50/70 h-screen">
          <Navbar/>
          <div className="flex space-x-7 max-w-7xl mx-auto px-4  pt-7">
            <div className="w-56">
              <SidePar />
            </div>
            <div className="flex-1">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
